{% set name = "openssh" %}
{% set version = "8.4p1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/{{ name }}-{{ version }}.tar.gz
  sha256: 5a01d22e407eb1c05ba8a8f7c654d388a13e9f226e4ed33bd38748dafa1d2b24

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - pkg-config
    - {{ compiler('c') }}
    - make
  host:
    - zlib
    - libedit
    - krb5
    - openssl

test:
  commands:
    - ssh-keygen -t rsa -b 4096 -f id_rsa -P do-not-pass-passwords
    - type -f scp
    - type -f sftp
    - type -f ssh
    - type -f ssh-add
    - type -f ssh-agent
    - type -f sshd
    - type -f ssh-keygen
    - type -f ssh-keyscan

about:
  home: https://www.openssh.com/
  license: BSD-style
  license_family: BSD
  license_file: LICENCE
  summary: A suite of secure networking utilities based on the SSH protocol
  description: |
    OpenSSH is the premier connectivity tool for remote login with the SSH
    protocol. It encrypts all traffic to eliminate eavesdropping, connection
    hijacking, and other attacks. In addition, OpenSSH provides a large suite
    of secure tunneling capabilities, several authentication methods, and
    sophisticated configuration options.
  dev_url: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/

extra:
  recipe-maintainers:
    - nehaljwani
