travis:
  secure:
    BINSTAR_TOKEN: e5FWWDmWU8YNJpAYjlIBeOmq+JWGhTEv8wwLRltdOy0vQoL2W/smeEefJ9kv/yf/TkELpf5XwEChByEjZEbr3QXyvsn6yYLUeYG+XEZfsaV9FXWn7/Zy/sVrFbaPqcM5hyEPgu61k3oRaHIwhz+f2NWRpZ6N5sw+uj+V6H33yWgnqB/eq1lxLW4fU5o/4zsbU4bwQ2XVGFzU1h5z6KD/DfGjltcczsmpuxXcQyRmDyOQQZzEBQ5VIeHI8Ovvkt/KXsYYZnupEoUKDxAM2BjZ22blnUmhr+ONsUzf/4TmCKK856W1o1VsJePVmBffh88RYouyVDyN7s6EWRSGvt+qzsOoFfYpft2K1kOYexJz2+Ytz76EYN63oHBd//xgIGcLLj4BV+7yVQcEsqacAKNi7ceSD2imiLy15xbIzndUXSCwXVJGtim6so3y11VLqXT2vdu+bA+FGzXrAS8iqBhrQ0bfEr1ni6bxpQ0mW+e7c9Pf6YuM3VCF+oBwpA3OhZ3fEZ/xFgObVk2VBdv6FzhtB6RVe33XKzUAZKhXOYyS1v70Nd8FMzzjoXxNM9lem38FMiAVnHp54IthrpjXuiPIclJqP3RgIfmmchdEFn5PIualDQU73zMIaPDx7FI2XHeyDCmhspQAcQXDfODJhp7eL808TYwXQBOWpEzo4Zl0X3U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
