travis:
  secure:
    BINSTAR_TOKEN: CIW+azrClNGEap2Nfh+mofA2S1OvRPFG6SfqKrZwb6gGWhAtTNqLu13CLiZ7ghtHwNNV6Vl+3ZJy2Aba4DIgZR+SgOsws5O86hufVNLDJYYBpi4Dd2NQSAo945NSyAGQ+j5lJjDqPrnz66R3N0XvCt57K0hnTxeLvzYFtV/CbNrVye/wMvR491hLZYyVYwZF5aiiU9D2WJEzkzyIIJ697ZIFraj1a3Jkt8K5jcsqzI5GdfZvxdSQSJhywvHJCRC8d+NiBQGDPC1TxDnInJt1r8Ly2DbYu/Phq+0NjXWkeRMidAf09d0HN8b0Eh6d8ddGTQwjQekWEjxV++ewFuCZwgcocnqQhzdJpYG0z4j/s6t0iCEn0Dfzj+8c1xQyTGnwOK3gJ6657ESUcx1d053WqtPhyIxhWxrO1DCtk4dxcUkzyAZfI2gWzr1X0iAZcOHoqaswIUwaxBg7dhMCaQHIbEAceT69JH35N8fpGUbO1h3b1YaOajkKi3inth6oJ3qx5rKsMsDdcJvs9eOiML1HHTvR4UIqSHvxZ3LFm355oajPeTxkTZwNb/HM+N+oQsvDFZQu7Yn4zap/s2EHsYy3vaaNp8ca4LLbbMtjnb1vL6hhJG015f+Z3+hCc8SbtqNhOJIPAg5GRQSCXZByfy22tNQKgc7UxraiP59wlSMMCfM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
